services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        WWWUSER: 1000
        WWWGROUP: 1000
    container_name: ez-php-websocket-tls-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
